import { defineConfig } from 'vitepress'

// ADR-016 §4 — the hub's presentation layer is meant to come from
// @middag-io/docs-theme. That package is still scaffolding (it currently
// exports only `name`, no VitePress preset), so the options below are defined
// locally. When the theme ships a config export, replace the inline options
// with it, e.g.:
//   import { defineHubConfig } from '@middag-io/docs-theme'
//   export default defineHubConfig({ /* hub overrides */ })

// Kept in sync with hub.config.json (middag-react version) — the injected docs
// land at docs/injected/middag-react/{version}/ during `npm run docs:prebuild`.
const MIDDAG_REACT_VERSION = '0.19.0'

export default defineConfig({
  title: 'MIDDAG Docs',
  description:
    'Unified documentation hub for MIDDAG libraries — build-time aggregated via edge storage (ADR-016).',
  lang: 'en',
  cleanUrls: true,
  lastUpdated: true,

  // docs/injected/** is generated by `npm run docs:prebuild` and is gitignored.
  // Injected payloads link to their own doc tree (e.g. /getting-started, /cli)
  // which the hub does not host yet, so those render as dead links. A target
  // allowlist like [/^\/injected\//] can't catch links that POINT OUT of the
  // subtree, so until the aggregator rewrites injected links this is a blanket
  // ignore — keeping the PoC build green while the payload layout isn't final.
  ignoreDeadLinks: true,

  head: [
    ['meta', { name: 'theme-color', content: '#0F172A' }],
    ['meta', { property: 'og:site_name', content: 'MIDDAG Docs' }],
  ],

  themeConfig: {
    siteTitle: 'MIDDAG Docs',
    nav: [
      { text: 'Home', link: '/' },
      { text: 'middag-react', link: `/injected/middag-react/${MIDDAG_REACT_VERSION}/` },
    ],
    sidebar: [
      {
        text: 'Libraries',
        items: [
          {
            text: `middag-react ${MIDDAG_REACT_VERSION}`,
            link: `/injected/middag-react/${MIDDAG_REACT_VERSION}/`,
          },
        ],
      },
    ],
    outline: { level: [2, 3] },
    socialLinks: [{ icon: 'github', link: 'https://github.com/middag-io' }],
    footer: { message: 'MIDDAG &copy; 2015-2026' },
    search: { provider: 'local' },
  },
})
